export enum LocalStorageKey {
  SHOPPING_CART = 'SHOPPING_CART',
  LOGGED_IN = 'LOGGED_IN',
  ACCESS_TOKEN = 'ACCESS_TOKEN',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
  LOGGED_IN_USER_ROLE = 'LOGGED_IN_USER_ROLE',
}
